"use strict";
const DEFAULT_PHOTO="data:image/svg+xml;charset=UTF-8,"+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="180" height="180"><rect width="180" height="180" fill="#e9e1cf"/><circle cx="90" cy="67" r="34" fill="#b38b2d"/><path d="M32 164c8-42 32-63 58-63s50 21 58 63" fill="#234b34"/></svg>`);
const treeContainer=document.getElementById("familyTree"),branchTitle=document.getElementById("branchTitle"),branchSummary=document.getElementById("branchSummary"),branchBreadcrumbName=document.getElementById("branchBreadcrumbName"),searchInput=document.getElementById("familySearch"),searchButton=document.getElementById("searchButton"),clearSearchButton=document.getElementById("clearSearchButton"),searchMessage=document.getElementById("searchMessage"),expandAllButton=document.getElementById("expandAllButton"),profileModal=document.getElementById("profileModal"),closeProfileButton=document.getElementById("closeProfileButton"),profilePhoto=document.getElementById("profilePhoto"),profileStatus=document.getElementById("profileStatus"),profileName=document.getElementById("profileName"),profileBiography=document.getElementById("profileBiography"),profileConnections=document.getElementById("profileConnections");
let familyData=null,peopleById=new Map(),branchRoot=null,isEverythingExpanded=true;
function getBranchId(){return new URLSearchParams(location.search).get("id");}
async function loadFamilyData(){try{const r=await fetch("data/family.json",{cache:"no-store"});if(!r.ok)throw new Error(`Could not load family.json (${r.status})`);familyData=await r.json();peopleById=new Map(familyData.people.map(p=>[p.id,p]));branchRoot=peopleById.get(getBranchId());if(!branchRoot)throw new Error("The selected relative was not found.");renderBranch();}catch(e){console.error(e);treeContainer.innerHTML=`<p class="tree-error">${e.message}<br><br><a href="tree.html">Return to the family-tree home view</a>.</p>`;branchTitle.textContent="Branch unavailable";}}
function initials(name){return(name||"?").split(/\s+/).filter(Boolean).slice(0,2).map(p=>p[0].toUpperCase()).join("");}
function createPhoto(p){if(p.photo){const i=document.createElement("img");i.src=p.photo;i.alt=`${p.displayName} profile`;i.className="tree-person-photo";return i;}const s=document.createElement("span");s.className="tree-person-photo person-initials";s.textContent=initials(p.displayName);return s;}
function collect(id,set=new Set()){if(set.has(id))return set;set.add(id);(peopleById.get(id)?.children||[]).forEach(c=>collect(c,set));return set;}
function generations(id,visited=new Set()){if(visited.has(id))return 0;visited.add(id);const kids=(peopleById.get(id)?.children||[]).filter(i=>peopleById.has(i));return kids.length?1+Math.max(...kids.map(k=>generations(k,new Set(visited)))):1;}
function renderBranch(){const ids=collect(branchRoot.id),count=Math.max(0,ids.size-1),gens=generations(branchRoot.id);branchTitle.textContent=`${branchRoot.displayName} Branch`;branchBreadcrumbName.textContent=`${branchRoot.displayName} Branch`;branchSummary.textContent=`${count} descendant${count===1?"":"s"} across ${gens} generation${gens===1?"":"s"}.`;treeContainer.innerHTML="";const ul=document.createElement("ul");ul.className="tree-root";ul.appendChild(createNode(branchRoot,new Set()));treeContainer.appendChild(ul);searchMessage.textContent=`${ids.size} relative${ids.size===1?"":"s"} displayed in this branch.`;}
function createNode(p,visited){const li=document.createElement("li");li.className="tree-person-item";li.dataset.searchName=`${p.displayName} ${p.profileName||""}`.toLowerCase();const row=document.createElement("div");row.className="tree-node-row";const next=new Set(visited);next.add(p.id);const kids=(p.children||[]).map(id=>peopleById.get(id)).filter(Boolean).filter(c=>!next.has(c.id));const btn=document.createElement("button");btn.type="button";btn.className="person-node";btn.appendChild(createPhoto(p));const text=document.createElement("span");text.className="person-node-text";const strong=document.createElement("strong");strong.textContent=p.displayName;const small=document.createElement("small");small.textContent=p.living?"Living relative":`${kids.length} child${kids.length===1?"":"ren"}`;text.append(strong,small);btn.appendChild(text);btn.addEventListener("click",()=>openProfile(p));row.appendChild(btn);if(kids.length){const t=document.createElement("button");t.type="button";t.className="branch-toggle";t.textContent="−";t.setAttribute("aria-expanded","true");row.appendChild(t);const ul=document.createElement("ul");ul.className="tree-children";kids.forEach(c=>ul.appendChild(createNode(c,next)));li.append(row,ul);t.addEventListener("click",()=>{const ex=t.getAttribute("aria-expanded")==="true";ul.hidden=ex;t.textContent=ex?"+":"−";t.setAttribute("aria-expanded",String(!ex));});}else li.appendChild(row);return li;}
function clearHighlights(){document.querySelectorAll(".person-node.search-match").forEach(n=>n.classList.remove("search-match"));}
function expandAncestors(el){let cur=el.parentElement;while(cur&&cur!==treeContainer){if(cur.classList.contains("tree-children")){cur.hidden=false;const toggle=cur.closest(".tree-person-item")?.querySelector(":scope > .tree-node-row .branch-toggle");if(toggle){toggle.textContent="−";toggle.setAttribute("aria-expanded","true");}}cur=cur.parentElement;}}
function searchFamily(){const term=searchInput.value.trim().toLowerCase();clearHighlights();if(!term){searchMessage.textContent="Enter a name to search.";return;}const matches=[...document.querySelectorAll(".tree-person-item")].filter(i=>i.dataset.searchName.includes(term));if(!matches.length){searchMessage.textContent=`No relative was found for “${searchInput.value.trim()}” in this branch.`;return;}matches.forEach(i=>{expandAncestors(i);i.querySelector(":scope > .tree-node-row .person-node")?.classList.add("search-match");});matches[0].querySelector(":scope > .tree-node-row .person-node")?.scrollIntoView({behavior:"smooth",block:"center"});searchMessage.textContent=`${matches.length} relative${matches.length===1?"":"s"} found.`;}
function clearSearch(){searchInput.value="";clearHighlights();}
function addConnection(label,ids){if(!ids?.length)return;const p=document.createElement("p"),s=document.createElement("strong");s.textContent=`${label}: `;p.append(s,document.createTextNode(ids.map(id=>peopleById.get(id)?.displayName||"Unknown relative").join(", ")));profileConnections.appendChild(p);}
function addText(label,text){if(!text)return;const p=document.createElement("p"),s=document.createElement("strong");s.textContent=`${label}: `;p.append(s,document.createTextNode(text));profileConnections.appendChild(p);}
function openProfile(p){profilePhoto.src=p.photo||DEFAULT_PHOTO;profilePhoto.alt=`${p.displayName} profile`;profileName.textContent=p.profileName||p.displayName;profileStatus.textContent=p.living?"Living family member":"Remembered family member";profileBiography.textContent=p.biography||"A biography has not been added yet.";profileConnections.innerHTML="";addConnection("Parents",p.parents);addConnection("Spouse",p.spouses);addConnection("Children",p.children);if(!p.living){addText("Born",[p.birth?.date,p.birth?.place].filter(Boolean).join(" — "));addText("Died",[p.death?.date,p.death?.place].filter(Boolean).join(" — "));}profileModal.hidden=false;document.body.classList.add("modal-open");}
function closeProfile(){profileModal.hidden=true;document.body.classList.remove("modal-open");}
function toggleAll(){isEverythingExpanded=!isEverythingExpanded;document.querySelectorAll(".tree-children").forEach(u=>u.hidden=!isEverythingExpanded);document.querySelectorAll(".branch-toggle").forEach(b=>{b.textContent=isEverythingExpanded?"−":"+";b.setAttribute("aria-expanded",String(isEverythingExpanded));});expandAllButton.textContent=isEverythingExpanded?"Collapse all":"Expand all";}
searchButton.addEventListener("click",searchFamily);clearSearchButton.addEventListener("click",clearSearch);expandAllButton.addEventListener("click",toggleAll);closeProfileButton.addEventListener("click",closeProfile);searchInput.addEventListener("keydown",e=>{if(e.key==="Enter")searchFamily();});profileModal.addEventListener("click",e=>{if(e.target===profileModal)closeProfile();});document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!profileModal.hidden)closeProfile();});loadFamilyData();
